name: api_test_proj
description: Api test project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  get: ^4.6.5
  http: ^0.13.5
  meta: ^1.8.0
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
